import { Link } from "@tanstack/react-router";
import { Diagram, Edge, Node, Note, Zone } from "../diagram";
import { CodeBlock, Doc, DocSection, DocTable, Figure, Term } from "../kit";

export function DashboardDoc() {
  return (
    <Doc
      slug="dashboard"
      lede="The dashboard is a React single-page app in web/. It has no state of its own beyond the URL and a query cache: every screen is a view of what the JSON API returns."
    >
      <DocSection page="dashboard" id="stack">
        <DocTable
          head={["Piece", "Choice"]}
          rows={[
            ["Language", "TypeScript in strict mode, React 19."],
            ["Tooling", "Vite+ (vp): dev server, build, format, lint, typecheck, and tests."],
            ["Routing", "TanStack Router, file-based, in src/routes/."],
            ["Server state", "TanStack Query. Hooks live in src/api/."],
            ["Primitives", "Base UI, wrapped in src/components/."],
            ["Icons", "lucide-react."],
            ["Styling", "CSS Modules and design tokens in src/styles/global.css."],
          ]}
        />
        <p>
          There is no Tailwind and no CSS-in-JS. The build output, <Term>web/dist</Term>, is
          embedded in the Go binary. See{" "}
          <Link to="/docs/$slug" params={{ slug: "local-development" }} hash="running">
            Running shed locally
          </Link>{" "}
          for the dev loop.
        </p>
      </DocSection>

      <DocSection page="dashboard" id="structure">
        <CodeBlock title="web/src">{`
routes/            file-based routes; thin, they pick a feature and load data
features/<name>/   screens and their pieces: projects, services, deployments, ...
components/        shared building blocks: Button, Card, Form, Overlay, Badge, ...
api/               fetch client, query and mutation hooks, types.ts
lib/               pure helpers: formatting, time, cron, logs
styles/            global.css: tokens, fonts, resets
showcase/          the /showcase route
main.tsx           router and query client
routeTree.gen.ts   generated by the router plugin, committed
`}</CodeBlock>
        <p>Data flows one way, from the server to the screen:</p>
        <Figure caption="A route's loader warms the cache, and components read it through the same query options.">
          <DataFlowDiagram />
        </Figure>
        <ul>
          <li>
            <strong>Routes</strong> in <Term>src/routes/</Term> are named by path. <Term>_app</Term>{" "}
            is the signed-in layout, and a <Term>$param</Term> segment is a route parameter. A
            route's <Term>loader</Term> calls <Term>queryClient.ensureQueryData</Term> so the page
            renders with data.
          </li>
          <li>
            <strong>Query hooks</strong> in <Term>src/api/</Term> pair a query key from{" "}
            <Term>keys.ts</Term> with a fetch, and mutations invalidate the keys they affect.
            Polling intervals live there too.
          </li>
          <li>
            <strong>The client</strong> in <Term>api/client.ts</Term> prefixes <Term>/api</Term>,
            sends JSON with cookies, and throws <Term>ApiError</Term> on a non-2xx response. Logs
            and status streams use <Term>useEventSource</Term> in <Term>api/events.ts</Term>.
          </li>
          <li>
            <strong>Types</strong> in <Term>api/types.ts</Term> mirror the API types in{" "}
            <Term>docs/design.md</Term>. Change both together.
          </li>
          <li>
            <strong>Features</strong> own their screens. Shared pieces move to{" "}
            <Term>components/</Term> only once a second feature needs them.
          </li>
        </ul>
        <p>
          After you add or rename a file in <Term>src/routes/</Term>, run the dev server or a build
          so the plugin regenerates <Term>routeTree.gen.ts</Term>, and commit it.
        </p>
      </DocSection>

      <DocSection page="dashboard" id="styling">
        <p>
          Every color is a token in <Term>src/styles/global.css</Term>, defined as a{" "}
          <Term>light-dark()</Term> pair, so a component never branches on theme. Use tokens, not
          raw values: <Term>--ink</Term> to <Term>--ink-4</Term> for text, <Term>--line</Term> for
          borders, <Term>--space-*</Term>, <Term>--r-*</Term>, and <Term>--text-*</Term> for sizes.
        </p>
        <ul>
          <li>
            <strong>Layering.</strong> Surfaces stack as <Term>--bg</Term>, <Term>--panel</Term>,{" "}
            <Term>--layer</Term>, <Term>--raised</Term>. <Term>LayerCard</Term> is a tinted outer
            sheet with the title, holding a raised inner sheet with the content.
          </li>
          <li>
            <strong>Crayons and tones.</strong> The hues (tangerine, sunflower, grass, teal, sky,
            grape, bubblegum, tomato) each have solid, <Term>-soft</Term>, <Term>-ink</Term>, and{" "}
            <Term>-line</Term> variants. Components take a <Term>tone</Term>, set{" "}
            <Term>data-tone</Term>, and read the variants from CSS. <Term>accent</Term> follows the
            user's accent hue.
          </li>
          <li>
            <strong>Browse them.</strong> The <Term>/showcase</Term> route renders the foundations
            and every shared component in light and dark.
          </li>
        </ul>
        <p>Rules:</p>
        <ul>
          <li>No gradients. Surfaces are flat and edges are crisp borders.</li>
          <li>Color means accent or status. Do not use it as decoration.</li>
          <li>A spinner means something is in progress. Do not use one for anything else.</li>
        </ul>
        <CodeBlock title="Badge.module.css (pattern)" lang="css">{`
.badge {
  background: var(--tone-soft);
  color: var(--tone-ink);
  border: 1px solid var(--tone-line);
}
[data-tone="grass"] {
  --tone-soft: var(--grass-soft);
  --tone-ink: var(--grass-ink);
  --tone-line: var(--grass-line);
}
`}</CodeBlock>
        <p>
          The snippet shows the idea. Look at <Term>components/Badge.module.css</Term> for the real
          rules.
        </p>
      </DocSection>

      <DocSection page="dashboard" id="writing-docs">
        <p>
          These pages live in <Term>src/features/docs/</Term>. A page has fixed section ids, because
          anchors, the sidebar, and the <Term>?</Term> tooltips all link to them.
        </p>
        <h3>Add a page</h3>
        <ol>
          <li>
            Add an entry to a group in <Term>registry.ts</Term> with a slug, a title, and its
            sections. Section ids are anchors, so renaming one breaks links.
          </li>
          <li>
            Write the component in <Term>pages/&lt;slug&gt;.tsx</Term>. Put page-specific styles in{" "}
            <Term>pages/&lt;slug&gt;.module.css</Term> and larger pieces in{" "}
            <Term>pages/&lt;slug&gt;/</Term>.
          </li>
          <li>
            Register it in <Term>pages/index.ts</Term>. The map is typed over every slug, so a
            missing page is a compile error.
          </li>
        </ol>
        <CodeBlock title="pages/example.tsx" lang="tsx">{`
export function ExampleDoc() {
  return (
    <Doc slug="example" lede="One sentence on what the reader will learn.">
      <DocSection page="example" id="first">
        <p>Plain p, ul, ol, h3, code, and a get prose styling.</p>
        <Figure caption="What the diagram shows.">
          <Diagram width={400} height={100} label="Client to server">
            <Node x={10} y={24} w={140} title="Client" sub="browser" />
            <Node x={250} y={24} w={140} title="Server" sub=":3000" tone="accent" emphasis />
            <Edge points={[[150, 50], [250, 50]]} label="/api" flow tone="accent" />
          </Diagram>
        </Figure>
        <CodeBlock title="shed.toml">{"[server]\\nurl = \\"...\\""}</CodeBlock>
      </DocSection>
    </Doc>
  );
}
`}</CodeBlock>
        <p>
          <Term>DocSection</Term> takes its heading from the registry and only accepts that page's
          section ids. Write in the second person, keep paragraphs short, and verify every claim
          against the code.
        </p>
        <h3>The kit</h3>
        <DocTable
          mono
          head={["Component", "Use"]}
          rows={[
            ["Doc, DocSection", "The page and an anchored section."],
            ["CodeBlock", "Code or terminal text with a copy button. Takes a title or a lang."],
            ["DocTable", "A compact reference table. mono sets the first column in monospace."],
            ["Term", "An inline identifier: a field, a status, a file name."],
            ["Figure", "Frames a diagram with a caption."],
            ["Demo", "Frames an interactive explainer that runs on sample data or reader input."],
          ]}
        />
        <h3>Diagrams</h3>
        <p>
          <Term>Diagram</Term> is an SVG canvas in viewBox units that scales to its container.
          Compose it from <Term>Zone</Term> (a labeled dashed region), <Term>Node</Term> (a box with
          a title and a monospace sub line), <Term>Edge</Term> (an arrow through points, with{" "}
          <Term>flow</Term>, <Term>dashed</Term>, and <Term>both</Term>), and <Term>Note</Term>{" "}
          (free text). Nothing measures text for you. A node title takes about 7.5 units per
          character and a sub line about 6.4, so check that every label fits its box and that no
          boxes overlap.
        </p>
        <h3>Demos</h3>
        <p>
          Use <Term>Demo</Term> when moving a slider or typing a value teaches more than a paragraph
          would. A demo runs entirely in the browser on sample data or what the reader types, and
          never calls the API. Put its logic in a pure function under{" "}
          <Term>features/docs/lib/</Term> with a test next to it, and keep the component thin.
        </p>
        <h3>Add a ? tooltip</h3>
        <p>
          A <Term>HelpTip</Term> is a small <Term>?</Term> that summarizes a concept on hover and
          links to its docs section. Add the topic to <Term>topics.ts</Term>, then place the tip
          next to the title or label it explains.
        </p>
        <CodeBlock title="topics.ts" lang="ts">{`
waitForCi: topic({
  page: "github",
  section: "wait-for-ci",
  summary: "Hold the deploy until every check run and status on the commit passes.",
}),
`}</CodeBlock>
        <CodeBlock title="in a component" lang="tsx">{`
<label>Wait for CI <HelpTip topic="waitForCi" /></label>
`}</CodeBlock>
        <p>
          <Term>topic()</Term> checks that the section belongs to the page at compile time, so a
          renamed section fails the build instead of leaving a dead link. Keep the summary to one or
          two sentences.
        </p>
        <p>
          Run <Term>bunx vp check --fix</Term> and <Term>bunx vp test run</Term> from{" "}
          <Term>web/</Term> before you finish.
        </p>
      </DocSection>
    </Doc>
  );
}

function DataFlowDiagram() {
  return (
    <Diagram width={800} height={270} label="How data flows from the API to the screen">
      <Zone x={10} y={30} w={560} h={170} label="dashboard · web/src" tone="sky" />
      <Node x={26} y={64} w={120} title="Route" sub="loader" />
      <Node x={176} y={64} w={130} title="Query hook" sub="api/*.ts" />
      <Node x={336} y={64} w={110} title="API client" sub="client.ts" />
      <Node x={176} y={140} w={130} h={44} title="Query cache" sub="keys.ts" />
      <Node x={26} y={140} w={120} h={44} title="Component" sub="features/" />
      <Node x={620} y={64} w={170} title="shed API" sub="/api/*" tone="accent" emphasis />
      <Node x={620} y={150} w={170} title="SQLite, Docker" sub="source of truth" />

      <Edge
        points={[
          [146, 90],
          [176, 90],
        ]}
        flow
        tone="accent"
      />
      <Edge
        points={[
          [306, 90],
          [336, 90],
        ]}
        flow
        tone="accent"
      />
      <Edge
        points={[
          [446, 90],
          [620, 90],
        ]}
        label="fetch"
        flow
        tone="accent"
      />
      <Edge
        points={[
          [705, 116],
          [705, 150],
        ]}
      />
      <Edge
        points={[
          [241, 116],
          [241, 140],
        ]}
        dashed
      />
      <Edge
        points={[
          [176, 162],
          [146, 162],
        ]}
        dashed
      />
      <Note x={10} y={226}>
        The route's loader and the component use the same query options, so the page opens with
      </Note>
      <Note x={10} y={244}>
        cached data. A mutation invalidates the keys it changed, and the hooks refetch.
      </Note>
    </Diagram>
  );
}
