/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app/projects/$projectId/settings'
import { Route as AppProjectsProjectIdServicesServiceIdRouteImport } from './routes/_app/projects/$projectId/services/$serviceId'
import { Route as AppProjectsProjectIdServicesServiceIdIndexRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/index'
import { Route as AppProjectsProjectIdServicesServiceIdBackupsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/backups'
import { Route as AppProjectsProjectIdServicesServiceIdLogsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/logs'
import { Route as AppProjectsProjectIdServicesServiceIdMetricsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/metrics'
import { Route as AppProjectsProjectIdServicesServiceIdSettingsRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/settings'
import { Route as AppProjectsProjectIdServicesServiceIdVariablesRouteImport } from './routes/_app/projects/$projectId/services/$serviceId/variables'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdRoute =
  AppProjectsProjectIdServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdIndexRoute =
  AppProjectsProjectIdServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdBackupsRoute =
  AppProjectsProjectIdServicesServiceIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdLogsRoute =
  AppProjectsProjectIdServicesServiceIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdMetricsRoute =
  AppProjectsProjectIdServicesServiceIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdSettingsRoute =
  AppProjectsProjectIdServicesServiceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)
const AppProjectsProjectIdServicesServiceIdVariablesRoute =
  AppProjectsProjectIdServicesServiceIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => AppProjectsProjectIdServicesServiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/showcase': typeof ShowcaseRoute
  '/settings': typeof AppSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/services/$serviceId': typeof AppProjectsProjectIdServicesServiceIdRouteWithChildren
  '/projects/$projectId/services/$serviceId/backups': typeof AppProjectsProjectIdServicesServiceIdBackupsRoute
  '/projects/$projectId/services/$serviceId/logs': typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  '/projects/$projectId/services/$serviceId/metrics': typeof AppProjectsProjectIdServicesServiceIdMetricsRoute
  '/projects/$projectId/services/$serviceId/settings': typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  '/projects/$projectId/services/$serviceId/variables': typeof AppProjectsProjectIdServicesServiceIdVariablesRoute
  '/projects/$projectId/services/$serviceId/': typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/showcase': typeof ShowcaseRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/services/$serviceId/backups': typeof AppProjectsProjectIdServicesServiceIdBackupsRoute
  '/projects/$projectId/services/$serviceId/logs': typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  '/projects/$projectId/services/$serviceId/metrics': typeof AppProjectsProjectIdServicesServiceIdMetricsRoute
  '/projects/$projectId/services/$serviceId/settings': typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  '/projects/$projectId/services/$serviceId/variables': typeof AppProjectsProjectIdServicesServiceIdVariablesRoute
  '/projects/$projectId/services/$serviceId': typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/showcase': typeof ShowcaseRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/services/$serviceId': typeof AppProjectsProjectIdServicesServiceIdRouteWithChildren
  '/_app/projects/$projectId/services/$serviceId/backups': typeof AppProjectsProjectIdServicesServiceIdBackupsRoute
  '/_app/projects/$projectId/services/$serviceId/logs': typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  '/_app/projects/$projectId/services/$serviceId/metrics': typeof AppProjectsProjectIdServicesServiceIdMetricsRoute
  '/_app/projects/$projectId/services/$serviceId/settings': typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  '/_app/projects/$projectId/services/$serviceId/variables': typeof AppProjectsProjectIdServicesServiceIdVariablesRoute
  '/_app/projects/$projectId/services/$serviceId/': typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/showcase'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/services/$serviceId'
    | '/projects/$projectId/services/$serviceId/backups'
    | '/projects/$projectId/services/$serviceId/logs'
    | '/projects/$projectId/services/$serviceId/metrics'
    | '/projects/$projectId/services/$serviceId/settings'
    | '/projects/$projectId/services/$serviceId/variables'
    | '/projects/$projectId/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/showcase'
    | '/settings'
    | '/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/services/$serviceId/backups'
    | '/projects/$projectId/services/$serviceId/logs'
    | '/projects/$projectId/services/$serviceId/metrics'
    | '/projects/$projectId/services/$serviceId/settings'
    | '/projects/$projectId/services/$serviceId/variables'
    | '/projects/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/showcase'
    | '/_app/settings'
    | '/_app/'
    | '/_app/projects/$projectId'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/services/$serviceId'
    | '/_app/projects/$projectId/services/$serviceId/backups'
    | '/_app/projects/$projectId/services/$serviceId/logs'
    | '/_app/projects/$projectId/services/$serviceId/metrics'
    | '/_app/projects/$projectId/services/$serviceId/settings'
    | '/_app/projects/$projectId/services/$serviceId/variables'
    | '/_app/projects/$projectId/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ShowcaseRoute: typeof ShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId': {
      id: '/_app/projects/$projectId/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/': {
      id: '/_app/projects/$projectId/services/$serviceId/'
      path: '/'
      fullPath: '/projects/$projectId/services/$serviceId/'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/backups': {
      id: '/_app/projects/$projectId/services/$serviceId/backups'
      path: '/backups'
      fullPath: '/projects/$projectId/services/$serviceId/backups'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdBackupsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/logs': {
      id: '/_app/projects/$projectId/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/services/$serviceId/logs'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/metrics': {
      id: '/_app/projects/$projectId/services/$serviceId/metrics'
      path: '/metrics'
      fullPath: '/projects/$projectId/services/$serviceId/metrics'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdMetricsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/settings': {
      id: '/_app/projects/$projectId/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/services/$serviceId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
    '/_app/projects/$projectId/services/$serviceId/variables': {
      id: '/_app/projects/$projectId/services/$serviceId/variables'
      path: '/variables'
      fullPath: '/projects/$projectId/services/$serviceId/variables'
      preLoaderRoute: typeof AppProjectsProjectIdServicesServiceIdVariablesRouteImport
      parentRoute: typeof AppProjectsProjectIdServicesServiceIdRoute
    }
  }
}

interface AppProjectsProjectIdServicesServiceIdRouteChildren {
  AppProjectsProjectIdServicesServiceIdBackupsRoute: typeof AppProjectsProjectIdServicesServiceIdBackupsRoute
  AppProjectsProjectIdServicesServiceIdLogsRoute: typeof AppProjectsProjectIdServicesServiceIdLogsRoute
  AppProjectsProjectIdServicesServiceIdMetricsRoute: typeof AppProjectsProjectIdServicesServiceIdMetricsRoute
  AppProjectsProjectIdServicesServiceIdSettingsRoute: typeof AppProjectsProjectIdServicesServiceIdSettingsRoute
  AppProjectsProjectIdServicesServiceIdVariablesRoute: typeof AppProjectsProjectIdServicesServiceIdVariablesRoute
  AppProjectsProjectIdServicesServiceIdIndexRoute: typeof AppProjectsProjectIdServicesServiceIdIndexRoute
}

const AppProjectsProjectIdServicesServiceIdRouteChildren: AppProjectsProjectIdServicesServiceIdRouteChildren =
  {
    AppProjectsProjectIdServicesServiceIdBackupsRoute:
      AppProjectsProjectIdServicesServiceIdBackupsRoute,
    AppProjectsProjectIdServicesServiceIdLogsRoute:
      AppProjectsProjectIdServicesServiceIdLogsRoute,
    AppProjectsProjectIdServicesServiceIdMetricsRoute:
      AppProjectsProjectIdServicesServiceIdMetricsRoute,
    AppProjectsProjectIdServicesServiceIdSettingsRoute:
      AppProjectsProjectIdServicesServiceIdSettingsRoute,
    AppProjectsProjectIdServicesServiceIdVariablesRoute:
      AppProjectsProjectIdServicesServiceIdVariablesRoute,
    AppProjectsProjectIdServicesServiceIdIndexRoute:
      AppProjectsProjectIdServicesServiceIdIndexRoute,
  }

const AppProjectsProjectIdServicesServiceIdRouteWithChildren =
  AppProjectsProjectIdServicesServiceIdRoute._addFileChildren(
    AppProjectsProjectIdServicesServiceIdRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdServicesServiceIdRoute: typeof AppProjectsProjectIdServicesServiceIdRouteWithChildren
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdServicesServiceIdRoute:
    AppProjectsProjectIdServicesServiceIdRouteWithChildren,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ShowcaseRoute: ShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
